### ISSUE TITLE
Minesweeper First Click Bug

### ISSUE THREAD

**Issue by Creeperman1524** [Creeperman1524/Pasta-Bot#16]
**Describe the bug**
Your first click is supposed to be guaranteed safe (and even a 0 I believe), which it is not here

**To Reproduce**
1. Start a minesweeper game
2. Randomly click someone as your first click
3. Sometimes, you'll get unlucky and click a bomb directly

**Expected behavior**
You are supposed to have your first click be guaranteed safe or a 0 tile

**Screenshots**
![image](https://user-images.githubusercontent.com/38088724/138581061-7c86dc09-e894-46cf-8142-c9c2d7f8e091.png)

**Comment by rufy545** [comment]
Can you please also also add a chess game or improve this command please. You are a great coder ^^

**Comment by Lcxd65** [comment]
yea I agree. You are amazing dude, also if you xan complete the command that you wanted to make such as hangman trivia. About hangman I suggest you to put a dropdown menu where you can pick all letters to guess the words
